/// Flutter icons IconFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconFont
///      fonts:
///       - asset: fonts/IconFont.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconFont {
  IconFont._();

  static const _kFontFam = 'IconFont';
  static const String? _kFontPkg = null;

  static const IconData inbox = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perspective_dice_three = IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_five = IconData(0xf523, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four = IconData(0xf524, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one = IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six = IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three = IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two = IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
